force-app/main/default/objects/Lv_Client__c/Lv_Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lv_Client__c/fields/Lv_Identification_Numero__c.field-meta.xml
<CustomField>
    <fullName>Lv_Identification_Numero__c</fullName>
    <label>Identification Numero</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lv_Client__c/fields/Lv_Prenom__c.field-meta.xml
<CustomField>
    <fullName>Lv_Prenom__c</fullName>
    <label>Prenom</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Lv_ClientCnt.cls
/**
 * ************************************************************
 *     * @Author abdoulaye.diop@/terangacloud.com
 *     * @date  08/05/2019
 *     * @description Wizard Controller for Lv_Client component
 * ************************************************************
 **/
public with sharing class Lv_ClientCnt {
    
    /**
     * @Author AD
     * @date  08/05/2019
     * @description Method to search a client
     * @param Integer numero, 
     * @param String prenom,
     * @param String nom
     **/
    @AuraEnabled
    public static Map<String, Object> searchClient(Integer numero, String prenom, String nom){
        Map<String, Object> response = new Map<String, Object>();
        prenom = '%' + prenom + '%';
        nom = '%' + nom + '%';

        try {
            List<Lv_Client__c> clients = [SELECT Id, Lv_Prenom__c, Name, Lv_Identification_Numero__c FROM Lv_Client__c
            WHERE Lv_Identification_Numero__c =:numero  OR Lv_Prenom__c LIKE :prenom OR Name LIKE :nom];

            response.put('clients', JSON.serialize(clients));
            response.put('error', false);
        } catch (Exception e) {
            response.put('error', true);
            response.put('message', e.getMessage());
            response.put('trace', e.getCause() + ' '+ e.getStackTraceString());
        }
        return response;
    }

    /**
     * @Author AD
     * @date  08/05/2019
     * @description Method to search a client
     * @param none
     **/
    @AuraEnabled
    public static Map<String, Object> createClient(Lv_Client__c client){
        Map<String, Object> response = new Map<String, Object>();
        try {
            insert client;
            response.put('client', client);
            response.put('error', false);
        } catch (Exception e) {
            response.put('error', true);
            response.put('message', e.getMessage());
            response.put('trace', e.getCause() + ' '+ e.getStackTraceString());
        }
        return response;
    }
    
}